const actions = {
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	SIGN_IN: 'SIGN_IN',
	SIGN_OUT: 'SIGN_OUT',
	SET_UPDATES: 'SET_UPDATES',
	EDIT_UPDATE: 'EDIT_UPDATE',
	FETCH_AGAIN: 'FETCH_AGAIN',
	UPDATE_TO_EDIT: 'UPDATE_TO_EDIT',
}

export default actions;