import Head from 'next/head';

export default function BezpieczenstwoDzieci() {
	return (
		<>
			<Head>
				<title> SJPS | Bezpieczenstwo Dzieci</title>
			</Head>

			<header className="header header--bezpieczenstwo-dzieci">

				<aside className="heading-wrapper">
					<h1>
						Bezpieczenstwo Dzieci
					</h1>
				</aside>

			</header>


			<main className="main main--bezpieczenstwo-dzieci">

				<section className="content-wrapper content-wrapper--center">

					<h2>Bezpieczenstwo dzieci</h2>

					<div className="text--left">

						<h5><strong>1.</strong> Przywozenie i odbior dzieci</h5>

						<br />

						<h5><strong>1.1</strong> Przywozenie</h5>

						<p>
							DZIECI PONIŻEJ 11-GO ROKU ŻYCIA POWINNY BYĆ PRZYPROWADZANE DO SZKOŁY POD OPIEKĄ OSOBY DOROSŁEJ. RODZICE LUB OSOBA UPOWAŻNIONA PRZEZ RODZICA JEST ODPOWIEDZIALNA ZA BEZPIECZNE PRZYBYCIE DZIECKA DO SZKOŁY, ORAZ ZA UPEWNIENIE SIĘ, ŻE DZIECKO ZNAJDUJE SIĘ W KLASIE ALBO W BUDYNKU SZKOLNYM. RODZICE POZOSTAJĄ ODPOWIEDZIALNI ZA BEZPIECZEŃSTWO DZIECI DO ROZPOCZĘCIA LEKCJI.
						</p>

						<br />

						<h5><strong>1.2</strong> Odbior</h5>

						<p>
							RODZICE MAJĄ OBOWIĄZEK PUNKTUALNEGO ODBIERANIA DZIECI Z TERENU SZKOŁY PO ZAKOŃCZONYCH ZAJĘCIACH SZKOLNYCH. RODZIC MA PRAWO UPOWAŻNIENIA INNEJ OSOBY DOROSŁEJ DO ODBIORU DZIECKA, W KTÓRYM TO PRZYPADKU RODZIC JEST ODPOWIEDZIALNY ZA POWIADOMIENIE NAUCZYCIELA DZIECKA, O TYM FAKCIE I PODANIE NAZWISKA OSOBY UPOWAŻNIONEJ. DZIECI POWINNY BYĆ ODBIERANE ZE SZKOŁY PUNKTUALNIE GDY ZAKOŃCZĄ SIĘ ZAJĘCIA.
							W PRZYPADKU KIEDY RODZIC PRZEWIDUJE SPÓŹNIENIE JEST ON ZOBOWIĄZANY DO NIEZWŁOCZNEGO POINFORMOWANIA O TYM SZKOŁY TELEFONUJĄC NA SZKOLNY NUMER TEL.
						</p>

						<br />

						<h5><strong>1.3</strong> Brak Kontaktu</h5>

						<p>
							W PRZYPADKU GDY KONTAKT Z RODZICEM JEST NIEMOŻLIWY, NAUCZYCIEL / DYREKCJA BĘDZIE KONTAKTOWAŁ SIĘ Z OSOBAMI (RODZINĄ LUB PRZYJACIÓŁMI RODZICÓW DZIECKA) KTÓRYCH NUMERY TELEFONÓW ZOSTAŁY PODANE NA FORMULARZU REJESTRACYJNYM.
							W PRZYPADKU GDY NIE MOŻNA SIĘ SKONTAKTOWAĆ Z ŻADNĄ Z WYŻEJ WYMIENIONYCH OSÓB PO UPŁYWIE 1 GODZINY, DYREKCJA SZKOŁY MOŻE SKONTAKTOWAĆ SIĘ Z POLICJĄ LUB PO PORADĘ LUB POMOC.
							DZIECKO NIE BĘDZIE TRANSPORTOWANE PRZEZ NAUCZYCIELI ANI INNYCH RODZICÓW BEZ UPRZEDNIEJ ZGODY RODZICÓW.
						</p>

						<br />

						<h5><strong>2</strong> Nieobecnosc</h5>

						<p>
							UCZĘSZCZANIE DO SOBOTNIEJ SZKOŁY JEST DOBROWOLNE I NIE MA USTAWOWEGO OBOWIĄZKU POSYŁANIA TAM DZIECI. JEDNAKŻE OCZEKUJE SIĘ, ŻE SZKOŁA BĘDZIE POINFORMOWANA O PRZEWIDYWALNEJ NIEOBECNOŚCI DZIECKA LUB TEŻ O DECYZJI WYCOFANIA DZIECKA ZE SZKOŁY. W PRZYPADKU KIEDY DZIECKO JEST NIEOBECNE W SZKOLE I JEŻELI POWSTANĄ OBAWY O BEZPIECZEŃSTWO DZIECKA, SZKOŁA BĘDZIE KONTAKTOWAŁA SIĘ Z RODZICAMI. JEŻELI BĘDZIE TO KONIECZNE, SZKOŁA MOŻE POINFORMOWAĆ O SWOICH OBAWACH ODPOWIEDNI URZĄD.
						</p>

						<br />

						<h5><strong>3</strong> Nagle przypadki i zdrowie</h5>

						<p>
							W PRZYPADKU GDYBY DZIECKO ULEGŁO WYPADKOWI, RODZICE DZIECKA BĘDĄ O TYM NATYCHMIASTOWO POINFORMOWANI. PRZY MAŁYCH OBRAŻENIACH OSOBA LUB NAUCZYCIEL PRZESZKOLONY W UDZIELANIU PIERWSZEJ POMOCY, UDZIELI DZIECKU PIERWSZEJ POMOCY W SZKOLE. DZIECKO POZOSTAJE POD OPIEKĄ NAUCZYCIELA DO MOMENTU, GDY JEST GOTOWE ŻEBY WRÓCIĆ DO KLASY LUB DO CZASU ODBIORU PRZEZ RODZICA. PRZY OBRAŻENIACH WYMAGAJĄCYCH POMOCY LEKARSKIEJ, ZOSTANIE WEZWANA KARETKA POGOTOWIA. ŻADNE LEKARSTWA NIE BĘDĄ PODAWANE DZIECKU BEZ UPRZEDNIEJ ZGODY RODZICÓW. RODZICE SĄ ZOBOWIĄZANI ZADEKLAROWAĆ NA POCZĄTKU KAŻDEGO ROKU SZKOLNEGO JAKIEKOLWIEK PRZEWLEKŁE CHOROBY NA KTÓRE DZIECKO CHORUJE (NP.. ASTMA, PADACZKA, ALERGIE). SZKOŁA NIE JEST W STANIE PONOSIĆ ODPOWIEDZIALNOŚCI ZA UDZIELANIE POMOCY MEDYCZNEJ DZIECIOM CHORUJĄCYM NA PRZEWLEKŁE CHOROBY, JEDNAKŻE W WYJĄTKOWYCH PRZYPADKACH PO UPRZEDNIM UZGODNIENIU I PISEMNYM OŚWIADCZENIU RODZICÓW, DYREKCJA MOŻE ZGODZIĆ SIĘ NA PODANIE W SYTUACJACH NAGŁYCH ODPOWIEDNICH LEKÓW DZIECKU.
						</p>

						<br />

						<h5><strong>4</strong> Fotografowanie</h5>

						<p>
							SZKOŁA BĘDZIE UBIEGAŁA SIĘ O ZGODĘ RODZICÓW NA ROBIENIE DZIECIOM ZDJĘĆ PODCZAS ZAJĘĆ LUB UROCZYSTOŚCI SZKOLNYCH I UMIESZCZANIE ICH NA STRONIE INTERNETOWEJ SZKOŁY BĄDŹ MEDIACH SPOŁECZNOŚCIOWYCH (PATRZ FORMULARZ ZGŁOSZENIOWY)
						</p>

						<br />

						<h5><strong>5</strong> Podejrzenie o molestowanie lub zaniedbywanie</h5>

						<p>
							JAKIEKOLWIEK ZNAKI WSKAZUJĄCE NA TO, ŻE DZIECKU DZIEJE SIĘ KRZYWDA LUB ŻE JEST ZANIEDBYWANE, BĘDĄ TRAKTOWANE BARDZO POWAŻNIE. W TAKIEJ SYTUACJI SZKOŁA BĘDZIE SIĘ DOKŁADNIE TRZYMAŁA WSKAZÓWEK ZAWARTYCH W OBOWIĄZUJĄCYM DOKUMENCIE GMINY LOKALNEJ SLOUGH I SKONTAKTUJE Z ODPOWIEDNIMI ORGANAMI.
						</p>

						<br />

						<h5><strong>6</strong> Narkotyki, lekarstwa ktore mozna nabyc bez recepty i uzywki</h5>

						<p>
							NARKOTYKI ORAZ UŻYWKI JAKIEGOKOLWIEK RODZAJU SĄ NIEDOZWOLONE NA TERENIE SZKOŁY. DZIECKO, KTÓRE ZAŻYWA LUB SPRZEDAJE NARKOTYKI, NAWET JEŻELI ZDARZYŁO SIĘ TO PO RAZ PIERWSZY ZOSTANIE WYDALONE ZE SZKOŁY. PICIE I POSIADANIE ALKOHOLU, PALENIE I POSIADANIE PAPIEROSÓW PRZEZ UCZNIÓW NA TERENIE SZKOŁY JEST SUROWO ZABRONIONE.
						</p>

						<br />

					</div>

				</section>

			</main>
		</>
	)
}
