import Head from 'next/head';

export default function Misja() {
	return (
		<>
			<Head>
				<title> SJPS | Misja</title>
			</Head>

			<header className="header header--misja">

				<aside className="heading-wrapper">
					<h1>
						Misja
					</h1>
				</aside>

			</header>

			<main className="main main--misja">

				<section className="content-wrapper content-wrapper--center">

					<h2>NASZA MISJA</h2>

					<blockquote className='quote'>“MÓW DZIECKU, ŻE JEST DOBRE, ŻE MOŻE, ŻE POTRAFI” ~ JANUSZ KORCZAK</blockquote>

					<br />

					<p>
						PRAGNIEMY BYĆ ZARÓWNO ATRAKCYJNYM JAK I BEZPIECZNYM MIEJSCEM DLA DZIECI. GORĄCO WIERZYMY, ŻE WSZYSCY TWÓRCY NASZEJ SZKOŁY – NAUCZYCIELE, UCZNIOWIE I RODZICE BĘDĄ MIELI WPŁYW NA JEJ FUNKCJONOWANIE. CHCEMY ABY PANOWAŁA W NIEJ ATMOSFERA POSZANOWANIA I WZAJEMNEJ AKCEPTACJI.
					</p>

					<br />

					<p>
						NASZE RELACJE OPIERAMY NA WSPÓLNEJ INTEGRACJI NAUCZYCIELI, UCZNIÓW I RODZICÓW PO TO BY TWORZYLI ONI WSPÓLNOTĘ SZKOLNA. NASZA MŁODA KADRA PEDAGOGICZNA OPRÓCZ NOWOCZESNYCH METOD NAUCZANIA WPROWADZA METODY AKTYWIZUJĄCE, KTÓRE ROZWIJAJĄ KREATYWNOŚĆ I SAMODZIELNOŚĆ UCZNIÓW.
					</p>

					<br />

					<p>
						CHCIELIBYŚMY ABY RODZICE WRAZ Z NAUCZYCIELAMI MOTYWOWALI UCZNIÓW DO NAUKI, DO PODEJMOWANIA NOWYCH WYZWAŃ I INICJATYW PO TO ABY AKTYWNIE UCZESTNICZYLI ONI W ŻYCIU KLASY, SZKOŁY I CAŁEJ PARAFII. W NASZEJ SZKOLE UCZYMY SZACUNKU DO TRADYCJI I KULTURY, TOLERANCJI I OTWARTOŚCI.
					</p>

					<br />

					<p>
						SZKOŁA IM. ŚW. SIOSTRY FAUSTYNY UMOŻLIWIA UCZNIOM PODTRZYMYWANIE POCZUCIA TOŻSAMOŚCI NARODOWEJ I JĘZYKOWEJ, WARTOŚCI CHRZEŚCIJAŃSKICH, NAUKĘ JĘZYKA POLSKIEGO ORAZ HISTORII I KULTURY POLSKIEJ.
					</p>

				</section>

			</main>
		</>
	)
}
