import Head from 'next/head';

export default function Patron() {
	return (
		<>
			<Head>

				<title>SJPS | Patron</title>

				<meta name="description" content="Z charyzmatu Św. Siostry Faustyny wyrosła nie tylko nowa szkoła duchowości, ale także apostolski ruch Bożego miłosierdzia." />

				<meta property="og:title" content="SJPS | Patron" />

				<meta property="og:description" content="Z charyzmatu Św. Siostry Faustyny wyrosła nie tylko nowa szkoła duchowości, ale także apostolski ruch Bożego miłosierdzia." />

				<meta property="og:url" content="https://szkolajezykapolskiegoslough.org/patron" />

			</Head>

			<header className="header header--patron">

				<aside className="heading-wrapper">
					<h1>
						Patron
					</h1>
				</aside>

			</header>

			<main className="main main--patron">

				<section className="content-wrapper content-wrapper--center">

					<h2>Patron</h2>

					<p>
						URODZIŁA SIĘ 25 SIERPNIA 1905 ROKU WE WSI GŁOGOWIEC JAKO TRZECIE SPOŚRÓD DZIESIĘCIORGA DZIECI W RODZINIE STANISŁAWA I MARIANNY KOWALSKICH. DWA DNI PÓŹNIEJ NA CHRZCIE ŚWIĘTYM W KOŚCIELE W ŚWINICACH WARCKICH OTRZYMAŁA IMIĘ HELENA. W WIEKU 9 LAT PRZYSTĄPIŁA DO KOMUNII ŚWIĘTEJ, DO SZKOŁY UCZĘSZCZAŁA NIECAŁE TRZY LATA, A POTEM POSZŁA NA SŁUŻBĘ DO ZAMOŻNYCH RODZIN W ALEKSANDROWIE LUDZKIM I ŁODZI. OD SIÓDMEGO ROKU ŻYCIA ODCZUWAŁA WEZWANIE DO SŁUŻBY BOŻEJ, ALE RODZICE NIE WYRAŻALI ZGODY NA JEJ WSTĄPIENIE DO KLASZTORU. PRZYNAGLONA JEDNAK WIZJĄ CIERPIĄCEGO CHRYSTUSA W LIPCU 1924 ROKU WYJECHAŁA DO WARSZAWY, BY SZUKAĆ MIEJSCA W KLASZTORZE.
					</p>

					<br />

					<p>
						DZIENNICZEK NALEŻY DO PEREŁ LITERATURY MISTYCZNEJ. ŚWIĘTA SIOSTRA FAUSTYNA PISAŁA GO W WILNIE I KRAKOWIE W LATACH 1934-38 NA WYRAŹNE POLECENIE PANA JEZUSA I ZE WZGLĘDU NA NAKAZ SWOICH SPOWIEDNIKÓW KS. MICHAŁA SOPOĆKI I O. JÓZEFA ANDRASZA SJ ORAZ ZA POZWOLENIEM PRZEŁOŻONYCH ZGROMADZENIA. PIERWSZE ZACHOWANE ZAPISKI POCHODZĄ Z LIPCA 1934 ROKU. WIADOMO ZE PIERWSZE NOTATKI SIOSTRA FAUSTYNA SPALIŁA, GDYŻ POD NIEOBECNOŚĆ W WILNIE KS. MICHAŁA ULEGŁA NAMOWOM RZEKOMEGO ANIOŁA, KTÓRYM BYŁ SZATAN. POTEM WILEŃSKI KIEROWNIK DUCHOWY KAZAŁ JEJ ODTWORZYĆ TO CO ZOSTAŁO ZNISZCZONE, DLATEGO, DZIENNICZEK W OBECNYM KSZTAŁCIE MA ZABURZONA CHRONOLOGIE, ZWŁASZCZA W PIERWSZYM ZESZYCIE: W BIEŻĄCE WYDARZENIA I PRZEŻYCIA AUTORKA WPLATA RELACJE I OPISY TYCH WYDARZEŃ, KTÓRE MIAŁY MIEJSCE WCZEŚNIEJ.
					</p>

					<br />

					<p>
						Z CHARYZMATU ŚW. SIOSTRY FAUSTYNY WYROSŁA NIE TYLKO NOWA SZKOŁA DUCHOWOŚCI, ALE TAKŻE APOSTOLSKI RUCH BOŻEGO MIŁOSIERDZIA, KTÓRY NA RÓŻNE SPOSOBY PODEJMUJE JEJ MISJE GŁOSZENIA ŚWIATU MIŁOSIERDZIA BOŻEGO POPRZEZ ŚWIADECTWO ŻYCIA, CZYNY SŁOWA I MODLITWĘ.
					</p>

					<br />

					<p>
						IDEA TEGO RUCHU ZOSTAŁA OBJAWIONA SIOSTRZE FAUSTYNIE W WILNIE W 1935 R. GDY JEZUS PRZEKAZAŁ JEJ SWE PRAGNIENIA DOTYCZĄCE ZAŁOŻENIA TAKIEGO ZGROMADZENIA, KTÓRE BY GŁOSIŁO MIŁOSIERDZIE BOGA ŚWIATU I WYPRASZAŁO JE DLA ŚWIATA. (DZ.436) POCZĄTKOWO SĄDZIŁA, ŻE MA OPUŚCIĆ ZGROMADZENIE I ZAŁOŻYĆ KLASZTOR KONTEMPLACYJNY, DLA KTÓREGO NAPISAŁA NAWET STRESZCZENIE REGUŁY ZAKONNEJ.
					</p>

					<br />

					<p>
						SIOSTRA FAUSTYNA PRAGNĘŁA BYĆ WIELKĄ ŚWIĘTĄ, WYNIESIONĄ DO CHWAŁY OŁTARZY (POR.DZ.150) WIELE RAZY PISAŁA NIE TYLKO O PRAGNIENIU ŚWIĘTOŚCI DLA SIEBIE, ALE TAKŻE Z NIEZWYKŁĄ KONSEKWENCJĄ DĄŻYŁA DO NIEJ. JEZU MÓJ PISAŁA -TY WIESZ, ŻE OD NAJWCZEŚNIEJSZYCH LAT PRAGNĘŁAM ZOSTAĆ WIELKĄ ŚWIĘTĄ, TO JEST, ŻE PRAGNĘŁAM CIĘ KOCHAĆ TAK WIELKĄ MIŁOŚCIĄ JAK CIĘ JESZCZE DOTYCHCZAS ŻADNA DUSZA NIE KOCHAŁA (DZ.1372)
					</p>

				</section>

			</main>
		</>
	)
}
