import Head from 'next/head';

export default function Wizja() {
	return (
		<>
			<Head>
				<title> SJPS | Wizja</title>
			</Head>

			<header className="header header--wizja">

				<aside className="heading-wrapper">
					<h1>
						Wizja
					</h1>
				</aside>

			</header>

			<main className="main main--wizja">

				<section className="content-wrapper content-wrapper--center">

					<h2>Nasza Wizja</h2>

					<p>
						PRAGNIEMY BYĆ ZARÓWNO ATRAKCYJNYM JAK I BEZPIECZNYM MIEJSCEM DLA DZIECI. GORĄCO WIERZYMY, ŻE WSZYSCY TWÓRCY NASZEJ SZKOŁY – NAUCZYCIELE , UCZNIOWIE I RODZICE BĘDĄ MIELI WPŁYW NA JEJ FUNKCJONOWANIE. CHCEMY ABY PANOWAŁA W NIEJ ATMOSFERA POSZANOWANIA I WZAJEMNEJ AKCEPTACJI. W MIARĘ ROZWOJU SZKOŁY BĘDZIEMY WYCHODZIĆ NA PRZECIW WYZWANIOM EDUKACYJNYM UCZNIÓW I RODZICÓW.
					</p>

					<br />

					<p>
						REALIZUJĄC ICH POTRZEBY I OCZEKIWANIA PRAGNIEMY ROZWIJAĆ NASZA OFERTĘ EDUKACYJNA TAK ABY KAŻDY UCZEŃ ZNALAZŁ TU ODPOWIEDNI KLIMAT I PRACOWAŁ EFEKTYWNIE. NASZE RELACJE OPIERAMY NA WSPÓLNEJ INTEGRACJI NAUCZYCIELI, UCZNIÓW I RODZICÓW PO TO BY TWORZYLI ONI WSPÓLNOTĘ SZKOLNA. NASZA MŁODA KADRA PEDAGOGICZNA OPRÓCZ NOWOCZESNYCH METOD NAUCZANIA WPROWADZA METODY AKTYWIZUJĄCE, KTÓRE ROZWIJAJĄ KREATYWNOŚĆ I SAMODZIELNOŚĆ UCZNIÓW.
					</p>

					<br />

					<p>
						CHCIELIBYŚMY ABY RODZICE WRAZ Z NAUCZYCIELAMI MOTYWOWALI UCZNIÓW DO NAUKI, DO PODEJMOWANIA NOWYCH WYZWAŃ I INICJATYW PO TO ABY AKTYWNIE UCZESTNICZYLI ONI W ŻYCIU KLASY, SZKOŁY I CAŁEJ PARAFII. W NASZEJ SZKOLE UCZYMY SZACUNKU DO TRADYCJI I KULTURY, TOLERANCJI I OTWARTOŚCI. SZKOŁA IM. ŚW. SIOSTRY FAUSTYNY UMOŻLIWIA UCZNIOM PODTRZYMYWANIE POCZUCIA TOŻSAMOŚCI NARODOWEJ I JĘZYKOWEJ ,WARTOŚCI CHRZEŚCIJAŃSKICH, NAUKĘ JĘZYKA POLSKIEGO ORAZ HISTORII I KULTURY POLSKIEJ.
					</p>

				</section>

			</main>
		</>
	)
}
